# Build step #1: build the React front end
FROM node:16-alpine as build-step

WORKDIR frontend/

ENV PATH ./node_modules/.bin:$PATH

COPY package.json package-lock.json ./
COPY ./src ./src
COPY ./public ./public
COPY .env ./

EXPOSE 3000
RUN npm install
CMD ["npm" ,"start"]


