# Build step #1: build the React front end
FROM node:16-alpine as build-step

WORKDIR frontend/

ENV PATH frontend/node_modules/.bin:$PATH

COPY frontend/package.json package-lock.json ./
COPY frontend/src/ src/
COPY frontend/public/ public/
COPY frontend/src/App.css frontend/src/App.js frontend/src/index.js frontend/src/logo.jpeg src/
COPY frontend/envfile .env

EXPOSE 3000
RUN npm install
CMD ["npm" ,"start"]